---
abstract: 'Read/Write .ini style files with as little code as possible'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 3.3
  File::Temp: 0.22
  Test::More: 0.47
configure_requires:
  Module::Build: 0.34
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Tiny
provides:
  Config::Tiny:
    file: lib/Config/Tiny.pm
    version: 2.20
requires:
  UNIVERSAL: 0
  perl: v5.8.1
  strict: 0
  utf8: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.20
